#
# Digital Voice Modem - Desktop Dispatch Console
#
# Full path to local key YAML file (see keys.example.clear for formatting)
#keyFile: "Full/Path/To/Keyfile.clear"
#
# FNE Masters
#
systems:
    # Textual name for internal and external reference to this system
  - name: "System 1"
    # Textual name to idenitify this peer in the FNE
    identity: "NYX GSMR1"
    # FNE Address
    address: "198.51.100.245"
    # FNE Port
    port: 63030
    # Peer ID for FNE
    peerId: 699001
    # Radio ID transmitted traffic will come from
    rid: "9001"
    # FNE Password
    password: "Centrunk!"
    # FNE Encrypted flag
    encrypted: false
    # Preshared FNE encryption key
    presharedKey: "123ABC1234"
    # Path to Radio Alias file for this system
    #aliasPath: "Full/Path/To/alias.yml"
    
#
# Zones
#
zones:
    # Textual name of the zone
  - name: "Zone 1"
    # List of channels
    channels:
        # Textual name of channel
      - name: "xOPS"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "500"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "p25"
        
      - name: "xTAC1"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "501"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "p25"
        
      - name: "xTAC2"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "502"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "p25"
        
      - name: "xTAC3"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "503"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "p25"
        
      - name: "xHELPDESK"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "505"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "p25"
        
      - name: "CM_RAIL"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "1000"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "p25"
        
      - name: "CM_RCML"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "1001"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "dmr"
        
      - name: "GSM-R!!"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "1001"
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "none"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "dmr"
        